import { Post } from './interfaces/Blog.interface';

export const POST: Post[] = [
    { id: 1, titulo: 'Dune 2024', texto: 'Dune: Parte 2 está a punto de llegar a los cines y es sencillo saber qué camino tomará. La primera entrega terminó con Paul Atreides uniéndose a los Fremen y viajando junto a ellos y su madre, Lady Jessica, a su ciudad natal. Y ese es el momento en el que empieza realmente a contarse la historia del protagonista. Paul seguirá su ascensión al poder, con las rebeliones resultantes que esto provocará, y conocerá a una buena cantidad de nuevos personajes en su camino. Una de ellas será la princesa Irulan, la adolescente hija del emperador Padisha Shaddam IV que se convertirá en su esposa por motivaciones políticas. En forma de pequeñísimo resumen libre de spoilers, se podría decir que la cinta mostrará la llegada a la vida adulta de su protagonista.', autor: 'Queypo', imagen: 'https://ase-ru-drupal-public--pro.s3.eu-central-1.amazonaws.com/sites/navi.axelspringer.es/public/media/image/2023/12/personajes-dune-parte-dos-2024-3240216.jpg', categoria: 'cine' },
    { id: 2, titulo: 'Invencible parte 2', texto: '"Invencible", basada en el rompedor cómic de Robert Kirkman, Cory Walker y Ryan Ottley, continúa explorando la compleja historia de Mark Grayson, un joven de 18 años diferente a todos los demás. ¿La principal diferencia? Su padre es (o era) el superhéroe más poderoso del planeta. Tras quedar conmocionado por la traición de su padre, Nolan, en la primera temporada, Mark lucha por reconstruir su vida mientras se enfrenta a un sinfín de nuevas amenazas. Esta temporada promete ahondar aún más en los conflictos internos de Mark, que lucha contra el miedo a convertirse en su padre sin ni siquiera darse cuenta.', autor: 'Queypo', imagen: 'https://es.web.img3.acsta.net/pictures/21/02/26/16/32/3176360.jpg', categoria: 'series' },
    { id: 3, titulo: 'Bizarrap', texto: 'Si ya se disfruta de una sesión de Bizarrap en los auriculares, imagínate lo que debe ser en directo. El artista ha ofrecido ya innumerables shows por todo el mundo y ha reunido a miles y miles de personas que siguen fielmente su trayectoria y que cantan cada uno de los versos de sus lanzamientos. Lanzamientos que se han convertido en himnos internacionales, como es el caso de su colaboración con Quevedo. Pero tampoco pasan desapercibidas sus sesiones con Young Miko y Villano Antillano, cuyas cifras de sus reproducciones demuestran que son la banda sonora de millones de personas.', autor: 'Queypo', imagen: 'https://static.wixstatic.com/media/839e94_45235cb92d63472da2d3e0d98312e390~mv2.jpg/v1/crop/x_0,y_139,w_1500,h_689/fill/w_644,h_590,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Bizarrap.jpg', categoria: 'musica' }

]

